---
project_name: 'ppath'

env:
  - 'GO111MODULE=on'

before:
  hooks:
    - 'go mod tidy'

builds:
  - id: 'ppath'
    main: 'main.go'
    binary: 'ppath'
    goos:
      - 'darwin'
      - 'linux'
      - 'windows'
    ignore:
      - goos: 'darwin'
        goarch: '386'

archives:
  - id: 'ppath'
    builds:
      - 'ppath'
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - 'CHANGELOG.md'
      - 'LICENSE-APACHE'
      - 'LICENSE-MIT'
      - 'README.md'

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  skip: true

nfpms:
  -
    id: 'ppath'
    package_name: ppath
    builds:
      - 'ppath'
    vendor: 'Olaf Alders'
    homepage: 'https://www.olafalders.com/'
    maintainer: 'Olaf Alders <https://github.com/oalders>'
    description: 'Lint included and excluded paths in a precious config file.'
    license: 'Apache 2.0 or MIT'
    provides:
      - ppath
    formats:
      - 'deb'
      - 'rpm'
    bindir: '/usr/bin'
    contents:
      - src: 'CHANGELOG.md'
        dst: '/usr/share/doc/ppath/CHANGELOG.md'
      - src: 'LICENSE-APACHE'
        dst: '/usr/share/doc/ppath/LICENSE-APACHE'
      - src: 'LICENSE-MIT'
        dst: '/usr/share/doc/ppath/LICENSE-MIT'
      - src: 'README.md'
        dst: '/usr/share/doc/ppath/README.md'
