[commands.golangci-lint]
type = "lint"
include = ["**/*.go", "foo"]
run_mode = "dirs"
cmd = [
    "golangci-lint",
    "run",
    "-c",
    "$PRECIOUS_ROOT/golangci.yml",
    "--allow-parallel-runners",
]
ok_exit_codes = 0

[commands.omegasort-gitignore]
type = "both"
include = "**/.gitignore"
cmd = [ "omegasort", "--sort", "path", "--unique" ]
lint_flags = "--check"
tidy_flags = "--in-place"
ok_exit_codes = 0
lint_failure_exit_codes = 1
ignore_stderr = [
    "The .+ file is not sorted",
    "The .+ file is not unique",
]

[commands.ppath]
type = "lint"
exclude = [
  "this-does-not-exist.txt",
  "nope*",
]
include = ["precious.toml"]
run_mode = "files"
cmd = ["go", "run", "main.go"]
ok_exit_codes = 0
